// Generated by CoffeeScript 2.3.2
// "use strict"

// class Contributor { 
// 	constructor(t) { 
// 		this.data = t
// 	}

// 	render(t) { 
// 		const li = Util.createAndAppend("li", t, { class : "contributor-item", "aria-label" : this.data.login, tabindex : 0})
// 		li.onclick = () => { window.open(this.data.html_url, "_blank") }
// 		li.onkeyup = t => { "Enter" === t.key && (t.preventDefault(),window.open(this.data.html_url,"_blank")) }
// 		Util.createAndAppend("img", li, { src : this.data.avatar_url, height : 48, class : "contributor-avatar"})
// 		const div = Util.createAndAppend("div", li, { class : "contributor-data"})
// 		Util.createAndAppend("div", div, { html : this.data.login })
// 		Util.createAndAppend("div", div, { html : this.data.contributions, class : "contributor-badge" })
// 	}
// }


//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ29udHJpYnV0b3IuanMiLCJzb3VyY2VSb290IjoiLi4iLCJzb3VyY2VzIjpbImNvZmZlZVxcQ29udHJpYnV0b3IuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSIsInNvdXJjZXNDb250ZW50IjpbIiMgXCJ1c2Ugc3RyaWN0XCJcclxuXHJcbiMgY2xhc3MgQ29udHJpYnV0b3IgeyBcclxuIyBcdGNvbnN0cnVjdG9yKHQpIHsgXHJcbiMgXHRcdHRoaXMuZGF0YSA9IHRcclxuIyBcdH1cclxuXHRcclxuIyBcdHJlbmRlcih0KSB7IFxyXG4jIFx0XHRjb25zdCBsaSA9IFV0aWwuY3JlYXRlQW5kQXBwZW5kKFwibGlcIiwgdCwgeyBjbGFzcyA6IFwiY29udHJpYnV0b3ItaXRlbVwiLCBcImFyaWEtbGFiZWxcIiA6IHRoaXMuZGF0YS5sb2dpbiwgdGFiaW5kZXggOiAwfSlcclxuIyBcdFx0bGkub25jbGljayA9ICgpID0+IHsgd2luZG93Lm9wZW4odGhpcy5kYXRhLmh0bWxfdXJsLCBcIl9ibGFua1wiKSB9XHJcbiMgXHRcdGxpLm9ua2V5dXAgPSB0ID0+IHsgXCJFbnRlclwiID09PSB0LmtleSAmJiAodC5wcmV2ZW50RGVmYXVsdCgpLHdpbmRvdy5vcGVuKHRoaXMuZGF0YS5odG1sX3VybCxcIl9ibGFua1wiKSkgfVxyXG4jIFx0XHRVdGlsLmNyZWF0ZUFuZEFwcGVuZChcImltZ1wiLCBsaSwgeyBzcmMgOiB0aGlzLmRhdGEuYXZhdGFyX3VybCwgaGVpZ2h0IDogNDgsIGNsYXNzIDogXCJjb250cmlidXRvci1hdmF0YXJcIn0pXHJcbiMgXHRcdGNvbnN0IGRpdiA9IFV0aWwuY3JlYXRlQW5kQXBwZW5kKFwiZGl2XCIsIGxpLCB7IGNsYXNzIDogXCJjb250cmlidXRvci1kYXRhXCJ9KVxyXG4jIFx0XHRVdGlsLmNyZWF0ZUFuZEFwcGVuZChcImRpdlwiLCBkaXYsIHsgaHRtbCA6IHRoaXMuZGF0YS5sb2dpbiB9KVxyXG4jIFx0XHRVdGlsLmNyZWF0ZUFuZEFwcGVuZChcImRpdlwiLCBkaXYsIHsgaHRtbCA6IHRoaXMuZGF0YS5jb250cmlidXRpb25zLCBjbGFzcyA6IFwiY29udHJpYnV0b3ItYmFkZ2VcIiB9KVxyXG4jIFx0fVxyXG4jIH0iXX0=
//# sourceURL=c:\github\foo\019-Coffee\coffee\Contributor.coffee