// Generated by CoffeeScript 2.3.2
// "use strict"

// class Repository {
// 	constructor(repository) {
// 		this.data = repository
// 	}

// 	render(parent) {
// 		const table = Util.createAndAppend("table", parent)
// 		const tbody = Util.createAndAppend("tbody", table)
// 		this.addRow(tbody, "Repository", `<a href="${this.data.html_url}" target="_blank">${this.data.name}</a>`)
// 		if (this.data.description) this.addRow(tbody,"Description", this.data.description)
// 		this.addRow(tbody, "Forks", this.data.forks)
// 		this.addRow(tbody, "Updated", new Date(this.data.updated_at).toLocaleString('sv'))
// 	}

// 	addRow(table, prompt, value) {
// 		const tr = Util.createAndAppend("tr", table);
// 		Util.createAndAppend("td", tr, { html : `${prompt} :`, class : "label"}),
// 		Util.createAndAppend("td", tr, { html : value })
// 	}

// 	fetchContributors() {
// 		return Util.fetchJSON(this.data.contributors_url)
// 	}

// }


//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUmVwb3NpdG9yeS5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxSZXBvc2l0b3J5LmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEiLCJzb3VyY2VzQ29udGVudCI6WyIjIFwidXNlIHN0cmljdFwiXHJcblxyXG4jIGNsYXNzIFJlcG9zaXRvcnkge1xyXG4jIFx0Y29uc3RydWN0b3IocmVwb3NpdG9yeSkge1xyXG4jIFx0XHR0aGlzLmRhdGEgPSByZXBvc2l0b3J5XHJcbiMgXHR9XHJcblxyXG4jIFx0cmVuZGVyKHBhcmVudCkge1xyXG4jIFx0XHRjb25zdCB0YWJsZSA9IFV0aWwuY3JlYXRlQW5kQXBwZW5kKFwidGFibGVcIiwgcGFyZW50KVxyXG4jIFx0XHRjb25zdCB0Ym9keSA9IFV0aWwuY3JlYXRlQW5kQXBwZW5kKFwidGJvZHlcIiwgdGFibGUpXHJcbiMgXHRcdHRoaXMuYWRkUm93KHRib2R5LCBcIlJlcG9zaXRvcnlcIiwgYDxhIGhyZWY9XCIke3RoaXMuZGF0YS5odG1sX3VybH1cIiB0YXJnZXQ9XCJfYmxhbmtcIj4ke3RoaXMuZGF0YS5uYW1lfTwvYT5gKVxyXG4jIFx0XHRpZiAodGhpcy5kYXRhLmRlc2NyaXB0aW9uKSB0aGlzLmFkZFJvdyh0Ym9keSxcIkRlc2NyaXB0aW9uXCIsIHRoaXMuZGF0YS5kZXNjcmlwdGlvbilcclxuIyBcdFx0dGhpcy5hZGRSb3codGJvZHksIFwiRm9ya3NcIiwgdGhpcy5kYXRhLmZvcmtzKVxyXG4jIFx0XHR0aGlzLmFkZFJvdyh0Ym9keSwgXCJVcGRhdGVkXCIsIG5ldyBEYXRlKHRoaXMuZGF0YS51cGRhdGVkX2F0KS50b0xvY2FsZVN0cmluZygnc3YnKSlcclxuIyBcdH1cclxuXHJcbiMgXHRhZGRSb3codGFibGUsIHByb21wdCwgdmFsdWUpIHtcclxuIyBcdFx0Y29uc3QgdHIgPSBVdGlsLmNyZWF0ZUFuZEFwcGVuZChcInRyXCIsIHRhYmxlKTtcclxuIyBcdFx0VXRpbC5jcmVhdGVBbmRBcHBlbmQoXCJ0ZFwiLCB0ciwgeyBodG1sIDogYCR7cHJvbXB0fSA6YCwgY2xhc3MgOiBcImxhYmVsXCJ9KSxcclxuIyBcdFx0VXRpbC5jcmVhdGVBbmRBcHBlbmQoXCJ0ZFwiLCB0ciwgeyBodG1sIDogdmFsdWUgfSlcclxuIyBcdH1cclxuXHJcbiMgXHRmZXRjaENvbnRyaWJ1dG9ycygpIHtcclxuIyBcdFx0cmV0dXJuIFV0aWwuZmV0Y2hKU09OKHRoaXMuZGF0YS5jb250cmlidXRvcnNfdXJsKVxyXG4jIFx0fVxyXG5cclxuIyB9Il19
//# sourceURL=c:\github\foo\019-Coffee\coffee\Repository.coffee