// Generated by CoffeeScript 2.3.2
var assert, print, range;

assert = require('assert').deepEqual;

range = require('lodash').range;

print = console.log;

print('##### begin #####');

assert(1 + 2, 3);

print('#####  end  #####');

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdC5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsidGVzdC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLElBQUEsTUFBQSxFQUFBLEtBQUEsRUFBQTs7QUFBQSxNQUFBLEdBQVMsT0FBQSxDQUFRLFFBQVIsQ0FBaUIsQ0FBQzs7QUFDM0IsS0FBQSxHQUFRLE9BQUEsQ0FBUSxRQUFSLENBQWlCLENBQUM7O0FBQzFCLEtBQUEsR0FBUSxPQUFPLENBQUM7O0FBQ2hCLEtBQUEsQ0FBTSxtQkFBTjs7QUFDQSxNQUFBLENBQU8sQ0FBQSxHQUFFLENBQVQsRUFBVyxDQUFYOztBQUNBLEtBQUEsQ0FBTSxtQkFBTiIsInNvdXJjZXNDb250ZW50IjpbImFzc2VydCA9IHJlcXVpcmUoJ2Fzc2VydCcpLmRlZXBFcXVhbFxyXG5yYW5nZSA9IHJlcXVpcmUoJ2xvZGFzaCcpLnJhbmdlXHJcbnByaW50ID0gY29uc29sZS5sb2dcclxucHJpbnQoJyMjIyMjIGJlZ2luICMjIyMjJylcclxuYXNzZXJ0IDErMiwzXHJcbnByaW50KCcjIyMjIyAgZW5kICAjIyMjIycpIl19
//# sourceURL=c:\github\foo\011-exercises\test.coffee